### ISSUE TITLE
STAThread Code fix

### ISSUE THREAD

**Issue by ChrisMaddock** [wachulski/nunit-migrator#26]
A common pattern in our remaining NUnit 2 tests is:

        [Test]
        [STAThread] 

The analyser picks this up nicely, but it's a pretty simple fix to:

    [Test, Appartment(ApparatmentState.STA)]

Would this be a good idea for another code-fix? I figure it should be restricted to where STAThread appears on the same method/class as TestAttribute/TestFixtureAttribute. 🙂 

Thanks for putting this tool together - it's coming in pretty useful on a project I'm looking at at the moment!

**Comment by wachulski** [comment]
Should be a straightforward task. I'll consider it for development soon.

**Comment by wachulski** [comment]
Closed by mistake. The feature is not released yet.

**Comment by ChrisMaddock** [comment]
Brilliant - thanks for adding that!
