### ISSUE TITLE
Comments and Regions Are Removed If the Order of ExpectedException Comes Before Test

### ISSUE THREAD

**Issue by aolszowka** [wachulski/nunit-migrator#29]
It appears that the Analzyer Fixer will remove Comments and Regions if the `ExpectedException` attribute is decorated ABOVE the `Test` Attribute

Consider the Following Test:

```csharp
using NUnit.Framework;
using System;
[TestFixture]
public class TestClass
{
    /// <summary>
    /// There was a comment here
    /// </summary>
    [ExpectedException(typeof(Exception))]
    [Test]
    public void TestMethod()
    {
        throw new Exception();
    }
}
```

After running the after running the Analzyer Fix the Comment has been destroyed:
```csharp
using NUnit.Framework;
using System;
[TestFixture]
public class TestClass
{
    [Test]
    public void TestMethod()
    {
        Assert.Throws<Exception>(() =>
        {
            throw new Exception();
        });
    }
}
```

This will also affect if you had regions:
```csharp
using NUnit.Framework;
using System;
[TestFixture]
public class TestClass
{
    #region Test
    [ExpectedException(typeof(Exception))]
    [Test]
    public void TestMethod()
    {
        throw new Exception();
    }
    #endregion
}
```

After running the Analyzer Fix:
```csharp

using NUnit.Framework;
using System;
[TestFixture]
public class TestClass
{
    [Test]
    public void TestMethod()
    {
        Assert.Throws<Exception>(() =>
        {
            throw new Exception();
        });
    }
    #endregion
}
```

This last one will at least throw a compiler error because the `#endregion` has no `#region` starting directive.

**Comment by aolszowka** [comment]
I have dug and dug but I just simply do not know enough about Roslyn Analzyers to figure out where this is occurring.

I have created several unit tests that reproduce the issue on my branch here https://github.com/aolszowka/nunit-migrator/compare/master...aolszowka:comment-and-region-truncation (unfortunately it looks like I made a mistake and should NEVER have committed my original changes into Master; again I am sorry I am still learning Git, otherwise it seems like I could have created a separate pull request for it)

**Comment by wachulski** [comment]
First thing @aolszowka - thank you for you contribution and thorough investigation you've done so far. 

And relax, you pushed the changes to *your* own fork's master (each of us has a personalized version of the repository and when I accept PRs GH just takes code from your fork and places it into mine). So, nothing bad really happened and that's why we have these PRs here.

I'll try to investigate it myself. At first glance it seems it's related to Roslyn's *trivia* concept (comments etc.). Again, thank you.

**Comment by wachulski** [comment]
I just checked that https://github.com/wachulski/nunit-migrator/blob/76c807337e8c1804181b0e245b0ca913f69d80b1/nunit.migrator/ExceptionExpectancy/CodeActions/ExceptionExpectancyCodeAction.cs#L81 lacks `.WithTriviaFrom(_method)`

If you want to fix it yourself, then please:
1. Get back to me and confirm, I'll assign this item to you
2. Use the existing test structure (opposing to resx files). The approach I've chosen is recommended by MS and widely accepted in Roslyn community.

**Comment by aolszowka** [comment]
I'm willing to give it a shot.

The reason I switched to RESX Files is it removed the need to quote/unquote a ton of stuff, I am willing to convert it to the existing test structure if I can find an easy way to escape quote the changes. Do you know of tooling to do this?
